on:
  push:

jobs:
  python_test:
    name: test python
    runs-on: ubuntu-latest
    steps:
      - name: Get python
        run: sudo apt-get install python3 python3-pip
      - name: Test python
        run: python3 --version
